In [83]:
import pandas as pd

In [85]:
df = pd.read_csv("C:/Users/emreo/OneDrive/Desktop/Machine_Learning_Studies/Tutorials/Youtube_Tutorials/codebasics/Dummy_Variables_and_One_Hot_Encoding/Exercise/car_prices.csv")
df

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [87]:
dummies = pd.get_dummies(df.get('Car Model'))
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [89]:
merged = pd.concat([dummies, df], axis='columns')
merged

,Audi A5,BMW X5,Mercedez Benz C class,Car Model,Mileage,Sell Price($),Age(yrs)
0,False,True,False,BMW X5,69000,18000,6
1,False,True,False,BMW X5,35000,34000,3
2,False,True,False,BMW X5,57000,26100,5
3,False,True,False,BMW X5,22500,40000,2
4,False,True,False,BMW X5,46000,31500,4
5,True,False,False,Audi A5,59000,29400,5
6,True,False,False,Audi A5,52000,32000,5
7,True,False,False,Audi A5,72000,19300,6
8,True,False,False,Audi A5,91000,12000,8
9,False,False,True,Mercedez Benz C class,67000,22000,6
10,False,False,True,Mercedez Benz C class,83000,20000,7
11,False,False,True,Mercedez Benz C class,79000,21000,7
12,False,False,True,Mercedez Benz C class,59000,33000,5

In [91]:
final = merged.drop(['Car Model', 'Audi A5'], axis='columns')
final

    BMW X5  Mercedez Benz C class  Mileage  Sell Price($)  Age(yrs)
0     True                  False    69000          18000         6
1     True                  False    35000          34000         3
2     True                  False    57000          26100         5
3     True                  False    22500          40000         2
4     True                  False    46000          31500         4
5    False                  False    59000          29400         5
6    False                  False    52000          32000         5
7    False                  False    72000          19300         6
8    False                  False    91000          12000         8
9    False                   True    67000          22000         6
10   False                   True    83000          20000         7
11   False                   True    79000          21000         7
12   False                   True    59000          33000         5

In [93]:
X = final.drop(['Sell Price($)'], axis='columns')
X

    BMW X5  Mercedez Benz C class  Mileage  Age(yrs)
0     True                  False    69000         6
1     True                  False    35000         3
2     True                  False    57000         5
3     True                  False    22500         2
4     True                  False    46000         4
5    False                  False    59000         5
6    False                  False    52000         5
7    False                  False    72000         6
8    False                  False    91000         8
9    False                   True    67000         6
10   False                   True    83000         7
11   False                   True    79000         7
12   False                   True    59000         5

In [95]:
y = final.get('Sell Price($)')
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [97]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [99]:
model.fit(X, y)

LinearRegression()

In [103]:
merged

,Audi A5,BMW X5,Mercedez Benz C class,Car Model,Mileage,Sell Price($),Age(yrs)
0,False,True,False,BMW X5,69000,18000,6
1,False,True,False,BMW X5,35000,34000,3
2,False,True,False,BMW X5,57000,26100,5
3,False,True,False,BMW X5,22500,40000,2
4,False,True,False,BMW X5,46000,31500,4
5,True,False,False,Audi A5,59000,29400,5
6,True,False,False,Audi A5,52000,32000,5
7,True,False,False,Audi A5,72000,19300,6
8,True,False,False,Audi A5,91000,12000,8
9,False,False,True,Mercedez Benz C class,67000,22000,6
10,False,False,True,Mercedez Benz C class,83000,20000,7
11,False,False,True,Mercedez Benz C class,79000,21000,7
12,False,False,True,Mercedez Benz C class,59000,33000,5

# 1) Prediction of the price of a mercedez benz that is 4 yr old with mileage 45000

In [107]:
model.predict([[0, 1, 45000, 4]])

C:\Users\emreo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721062])

# 2) Prediction of the price of a BMW X5 that is 7 yr old with mileage 86000

In [109]:
model.predict([[1, 0, 86000, 7]])

C:\Users\emreo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])

# 3) score (accuracy) of the model

In [ ]:
model.score(X, y)